name: On Push CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Grant rights
        run: chmod +x build.gradle.kts gradlew gradle

      - name: Submit dependencies for GitHub analysis
        uses: mikepenz/gradle-dependency-submission@v1.0.0
        with:
          gradle-build-module: ":app"

      - name: Build with Gradle
        id: build
        run: ./gradlew build
